DROP DATABASE IF EXISTS task_db;

CREATE DATABASE task_db;

USE task_db;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name TEXT NULL,
email TEXT NULL,
password TEXT NULL,
updated_at DATE,
created_at DATE

);

DROP TABLE IF EXISTS categories;
CREATE TABLE categories (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
title TEXT NULL,
description TEXT NULL,
status TINYINT,
   
);

